/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import CommandMessages.CommandMessageSender;
import CommandMessages.tBladeControlSetChannelMsg;
import CommandMessages.tBladeControlSetPowerMsg;
import Util.Converter;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Jake
 */
public class BladeColorScreen extends javax.swing.JFrame {

    /**
     * Creates new form BladeColorScreen
     * @param aMessageSndr - Message sender
     * @param aTargetSettings - Target settings manager
     */
    public BladeColorScreen(CommandMessageSender aMessageSndr,
                            TargetSettingsManager aTargetSettings)
    {
        initComponents();
        
        this.setTitle("JakeSoft's STREAM " + Constants.VERSION + " - Blade Color");
        mMessageSndr = aMessageSndr;
        mTargetSettings = aTargetSettings;
        mColorPresetIndex = 0;
        
        this.setBackground(Color.black);
        this.getContentPane().setBackground(Color.black);

        SetChannelLimmts();
    }

    /**
     * Sets the index of the color preset to modify.
     * @param aColorIndex - Color index to modify.
     */
    public void SetColorPresetIndex(int aColorIndex)
    {
        System.out.print("BladeColorScreen preset color set to ");
        System.out.println(aColorIndex);
        
        mColorPresetIndex = aColorIndex;
               
        Integer lCh1 = Converter.byte2int(
            mTargetSettings.GetBladeColors().get(aColorIndex).mChannel1);
        Integer lCh2 = Converter.byte2int(
            mTargetSettings.GetBladeColors().get(aColorIndex).mChannel2);
        Integer lCh3 = Converter.byte2int(
            mTargetSettings.GetBladeColors().get(aColorIndex).mChannel3);

         this.mChnlSlider1.setValue(lCh1);
         this.mChnlSlider2.setValue(lCh2);
         this.mChnlSlider3.setValue(lCh3);
         
         this.mChnlSlider1Lbl.setText(lCh1.toString());
         this.mChnlSlider2Lbl.setText(lCh2.toString());
         this.mChnlSlider3Lbl.setText(lCh3.toString());
    }
    
    public void SetBladeConfigScreen(BladeConfigScreen aScreen)
    {
        mBladeConfigScreen = aScreen;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mChnlSlider1 = new javax.swing.JSlider();
        mChnlSlider2 = new javax.swing.JSlider();
        mChnlSlider3 = new javax.swing.JSlider();
        mChnlSlider1Lbl = new javax.swing.JLabel();
        mChnlSlider2Lbl = new javax.swing.JLabel();
        mChnlSlider3Lbl = new javax.swing.JLabel();
        mOkButton = new javax.swing.JButton();
        mPreviewCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 330));

        mChnlSlider1.setBackground(new java.awt.Color(0, 0, 0));
        mChnlSlider1.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider1.setMaximum(255);
        mChnlSlider1.setToolTipText("");
        mChnlSlider1.setValue(0);
        mChnlSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider1StateChanged(evt);
            }
        });

        mChnlSlider2.setBackground(new java.awt.Color(0, 0, 0));
        mChnlSlider2.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider2.setMaximum(255);
        mChnlSlider2.setToolTipText("");
        mChnlSlider2.setValue(0);
        mChnlSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider2StateChanged(evt);
            }
        });

        mChnlSlider3.setBackground(new java.awt.Color(0, 0, 0));
        mChnlSlider3.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider3.setMaximum(255);
        mChnlSlider3.setToolTipText("");
        mChnlSlider3.setValue(0);
        mChnlSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider3StateChanged(evt);
            }
        });

        mChnlSlider1Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mChnlSlider1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider1Lbl.setText("jLabel1");

        mChnlSlider2Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mChnlSlider2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider2Lbl.setText("jLabel1");

        mChnlSlider3Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mChnlSlider3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        mChnlSlider3Lbl.setText("jLabel1");

        mOkButton.setText("OK");
        mOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOkButtonActionPerformed(evt);
            }
        });

        mPreviewCheckbox.setBackground(new java.awt.Color(0, 0, 0));
        mPreviewCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        mPreviewCheckbox.setText("Preview");
        mPreviewCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mPreviewCheckboxStateChanged(evt);
            }
        });
        mPreviewCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPreviewCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mPreviewCheckbox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mChnlSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                            .addComponent(mChnlSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mChnlSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mChnlSlider2Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mChnlSlider1Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mChnlSlider3Lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(96, 96, 96))))
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(mOkButton)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mChnlSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mChnlSlider1Lbl))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mChnlSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mChnlSlider2Lbl))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mChnlSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mChnlSlider3Lbl))
                .addGap(26, 26, 26)
                .addComponent(mPreviewCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(mOkButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mChnlSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider1StateChanged
        if(this.mPreviewCheckbox.getModel().isSelected())
        {
            SendBladeChannelSettings(true);
        }
        else
        {
            SendBladeChannelSettings(false);
        }
    }//GEN-LAST:event_mChnlSlider1StateChanged

    private void mChnlSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider2StateChanged
       if(this.mPreviewCheckbox.getModel().isSelected())
        {
            SendBladeChannelSettings(true);
        }
        else
        {
            SendBladeChannelSettings(false);
        }
    }//GEN-LAST:event_mChnlSlider2StateChanged

    private void mChnlSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider3StateChanged
       if(this.mPreviewCheckbox.getModel().isSelected())
        {
            SendBladeChannelSettings(true);
        }
        else
        {
            SendBladeChannelSettings(false);
        }
    }//GEN-LAST:event_mChnlSlider3StateChanged

    private void mOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOkButtonActionPerformed
        //De-select the preiview checkbox
        mPreviewCheckbox.setSelected(false);
        
        //Turn off the blade
        CommandMessages.tBladeControlSetPowerMsg lsPwrOffMsg
                = new CommandMessages.tBladeControlSetPowerMsg();
        lsPwrOffMsg.mPower = 0;
        mMessageSndr.SendMessage(lsPwrOffMsg);
              
        //Snag reference to the blade colors
        ArrayList<Settings.tBladeColor> lColors =
                mTargetSettings.GetBladeColors();
        
        //Snag user input channel values
        Integer lChn1 = (Integer)this.mChnlSlider1.getValue();
        Integer lChn2 = (Integer)this.mChnlSlider2.getValue();
        Integer lChn3 = (Integer)this.mChnlSlider3.getValue();
        
        //Update the color preset with user values
        lColors.get(mColorPresetIndex).mChannel1 = lChn1.byteValue();
        lColors.get(mColorPresetIndex).mChannel2 = lChn2.byteValue();
        lColors.get(mColorPresetIndex).mChannel3 = lChn3.byteValue();
        
        System.out.print("Set color preset [");
        System.out.print(mColorPresetIndex);
        System.out.print("]:");
        System.out.print(lColors.get(mColorPresetIndex).mChannel1);
        System.out.print(",");
        System.out.print(lColors.get(mColorPresetIndex).mChannel2);
        System.out.print(",");
        System.out.print(lColors.get(mColorPresetIndex).mChannel3);
        
        //Save new color presets
        mTargetSettings.SetColorPresets(lColors);
        
        if(null != mBladeConfigScreen)
        {
            mBladeConfigScreen.setBounds(this.getBounds());
            mBladeConfigScreen.setVisible(true);
            mBladeConfigScreen.UpdateDisplay();
            this.setVisible(false);
        }
    }//GEN-LAST:event_mOkButtonActionPerformed

    private void mPreviewCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mPreviewCheckboxStateChanged
//        if(this.mPreviewCheckbox.getModel().isSelected())
//        {
//            //Turn on the blade
//            tBladeControlSetPowerMsg lSetPwrMsg = new tBladeControlSetPowerMsg();
//            lSetPwrMsg.mPower = 0;
//            mMessageSndr.SendMessage(lSetPwrMsg);            
//        }
//        else
//        {
//            //Turn off the blade
//            tBladeControlSetPowerMsg lSetPwrMsg = new tBladeControlSetPowerMsg();
//            lSetPwrMsg.mPower = 0;
//            mMessageSndr.SendMessage(lSetPwrMsg);
//        }
    }//GEN-LAST:event_mPreviewCheckboxStateChanged

    private void mPreviewCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPreviewCheckboxActionPerformed
        if(this.mPreviewCheckbox.getModel().isSelected())
        {
            System.out.println("Enable color preview.");            
            //Turn on the blade
            SendBladeChannelSettings(true);
            
        }
        else
        {
            System.out.println("Disable color preview.");            
            //Turn off the blade
            tBladeControlSetPowerMsg lSetPwrMsg = new tBladeControlSetPowerMsg();
            lSetPwrMsg.mPower = 0;
            mMessageSndr.SendMessage(lSetPwrMsg);
            
        }
    }//GEN-LAST:event_mPreviewCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BladeColorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BladeColorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BladeColorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BladeColorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BladeColorScreen().setVisible(true);
//            }
//        });
//    }

    private void SendBladeChannelSettings(boolean aTurnOn)
    {
        Integer lValue0 = mChnlSlider1.getValue();
        Integer lValue1 = mChnlSlider2.getValue();
        Integer lValue2 = mChnlSlider3.getValue();
        
        mChnlSlider1Lbl.setText(lValue0.toString());
        mChnlSlider2Lbl.setText(lValue1.toString());
        mChnlSlider3Lbl.setText(lValue2.toString());
        
        if(aTurnOn)
        {
            //Set Channel 0
            tBladeControlSetChannelMsg lSetChnlMsg = new tBladeControlSetChannelMsg();
            lSetChnlMsg.mChannel = 0;
            lSetChnlMsg.mValue = lValue0.byteValue();
            mMessageSndr.SendMessage(lSetChnlMsg);

            //Set Channel 1
            lSetChnlMsg.mChannel = 1;
            lSetChnlMsg.mValue = lValue1.byteValue();
            mMessageSndr.SendMessage(lSetChnlMsg);

            //Set Channel 2
            lSetChnlMsg.mChannel = 2;
            lSetChnlMsg.mValue = lValue2.byteValue();
            mMessageSndr.SendMessage(lSetChnlMsg);

            tBladeControlSetPowerMsg lSetPwrMsg = new tBladeControlSetPowerMsg();
            lSetPwrMsg.mPower = 1;
            mMessageSndr.SendMessage(lSetPwrMsg);
        }
    }
        
    private void SetChannelLimmts()
    {      
        Util.tGuiConfig lGuiConfig = Util.GuiConfigManager.GetInstance().GetGuiConfig();
        
        mChnlSlider1.getModel().setMaximum(lGuiConfig.mChannel1Limmit);
        mChnlSlider2.getModel().setMaximum(lGuiConfig.mChannel2Limmit);
        mChnlSlider3.getModel().setMaximum(lGuiConfig.mChannel3Limmit);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider mChnlSlider1;
    private javax.swing.JLabel mChnlSlider1Lbl;
    private javax.swing.JSlider mChnlSlider2;
    private javax.swing.JLabel mChnlSlider2Lbl;
    private javax.swing.JSlider mChnlSlider3;
    private javax.swing.JLabel mChnlSlider3Lbl;
    private javax.swing.JButton mOkButton;
    private javax.swing.JCheckBox mPreviewCheckbox;
    // End of variables declaration//GEN-END:variables

    CommandMessageSender mMessageSndr;
    TargetSettingsManager mTargetSettings;
    int mColorPresetIndex;
    BladeConfigScreen mBladeConfigScreen;
}
