/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import ResponseMessages.ResponseMessageSubscriber;
import CommandMessages.CommandMessageSender;
import ResponseMessages.ResponseMessageReceiver;
import ResponseMessages.ResponseMessageBase;
import com.fazecast.jSerialComm.SerialPort;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Jake
 */
public class ConnectScreen
        extends javax.swing.JFrame
        implements ResponseMessageSubscriber{

    /**
     * Creates new form ConnectScreen
     */
    public ConnectScreen() {
        initComponents();
        this.setTitle("JakeSoft's STREAM " + Constants.VERSION );
        initComPortComboBox();
        initInstallFirmwareButton();
        
        mAckCount = 0;
        this.mStatusLabel.setText("");
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/STREAM.png")));
    }

    @Override
    public void NotifyMessage(ResponseMessageBase aMsg)
    {
        if(ResponseMessages.MessageIds.eeAck.ordinal() == aMsg.mMsgId)
        {
            mAckCount++;
        }
    }
    
    private void initInstallFirmwareButton()
    {
        File lFirmwareFolder = new File("firmware");
        
        if(lFirmwareFolder.exists() && lFirmwareFolder.isDirectory())
        {
            mInstallFirmwareButton.setVisible(true);
        }
        else
        {
            mInstallFirmwareButton.setVisible(false);
        }
    }
       /**
     * Initialize the Com port selection box with valid options.
     */
    private void initComPortComboBox()
    {
        
        //Fetch avaiable COM ports
        mPorts = SerialPort.getCommPorts();
        
        //Populate the com port selection combo box with available options
        int i = 0;
        for(SerialPort port : mPorts)
        {
           mComPortComboBox.addItem(port.getSystemPortName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mComPortComboBox = new javax.swing.JComboBox<>();
        mConnectButton = new javax.swing.JButton();
        mStatusLabel = new javax.swing.JLabel();
        mInstallFirmwareButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mConnectButton.setText("Connect");
        mConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnectButtonActionPerformed(evt);
            }
        });

        mStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mStatusLabel.setText("Status");

        mInstallFirmwareButton.setBackground(new java.awt.Color(255, 102, 102));
        mInstallFirmwareButton.setText("Install Firmware");
        mInstallFirmwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInstallFirmwareButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mComPortComboBox, 0, 253, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mInstallFirmwareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mConnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mComPortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mConnectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mInstallFirmwareButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(mStatusLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnectButtonActionPerformed
        mHomeScreen = null;
        System.gc();
        
        mStatusLabel.setText("Connecting...");
        System.out.println("Connecting...");
               
        int lSelectedComPort = mComPortComboBox.getSelectedIndex();
        
        mSerialPort = mPorts[lSelectedComPort];
        
        //Try to open the port
        if(mSerialPort.openPort())
        {
            System.out.println("Port opened successfully.");
            
            //Set connection parameters
            mSerialPort.setComPortParameters(9600, 8, 1, SerialPort.NO_PARITY);
            mSerialPort.setComPortTimeouts(SerialPort.TIMEOUT_READ_BLOCKING, 0, 0);
            mSerialPort.setComPortTimeouts(SerialPort.TIMEOUT_WRITE_BLOCKING, 0, 0);
        
            //Clear any garbage off the serial port
            while(mSerialPort.bytesAvailable() > 0)
            {
                byte[] lGarbageByte = new byte[1];
                mSerialPort.readBytes(lGarbageByte, 1);
            }
            
            //Create message receiver
            mMessageRcvr = new ResponseMessageReceiver(mSerialPort);
            mMessageRcvr.Subscribe(this);
            new Thread(mMessageRcvr).start();
            
            //Create message sender
            mMessageSndr = new CommandMessageSender(mSerialPort);
            mStatusLabel.setText("Connected.");
            System.out.println("Connected.");
            
            try
            {
                Thread.sleep(2000);
            }
            catch(InterruptedException lEx)
            {
                lEx.printStackTrace();
            }
            
            for(int lTry = 0; lTry < 120 & mAckCount < 3; lTry++)
            {
                Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestAck.ordinal();
                mMessageSndr.SendOneByteMessage(lMsgId.byteValue());
                
                try
                {
                    Thread.sleep(500);
                }
                catch(InterruptedException lEx)
                {
                    lEx.printStackTrace();
                }
            }
            
            if(mAckCount < 3)
            {
                mStatusLabel.setText("Handshake failed.");
                System.out.println("Handshake failed.");
                this.mMessageRcvr.Stop();
                this.mMessageRcvr = null;
                this.mMessageSndr = null;
                this.mSerialPort.closePort();
                this.mSerialPort = null;
                this.mAckCount = 0;
                this.mTargetSettings = null;
                System.gc();
                
                return; //Quit, we can't start a session
            }
            
            //Create target settings manager
            mTargetSettings = new TargetSettingsManager(mMessageSndr, mMessageRcvr);
            mTargetSettings.Init();
            
            //Try to fetch protocol and version data from the target
            mTargetSettings.FetchProtocolVersionFromTarget();
            if(null == mTargetSettings.GetProtocolVersion())
            {
                System.err.println("Protocol version invalid.");
                mStatusLabel.setText("Protocol version invalid.");
                return; //We can't connect without knowing protocol version
            }
            else if(!Constants.PROTOCOLVERSION.equalsIgnoreCase(mTargetSettings.GetProtocolVersion()))
            {
                System.err.println("Protocol version mismatch.");
                String lStatusText = "Protocol version mismatch! Expected: ";
                lStatusText += Constants.PROTOCOLVERSION.toString();
                lStatusText += " Target is using: ";
                lStatusText += mTargetSettings.GetProtocolVersion().toString();
                
                mStatusLabel.setText(lStatusText);
                return; //Punt on protocol version mismatch
            }
            
            mTargetSettings.FetchFirmwareVersionFromTarget();
            if(null == mTargetSettings.GetFirmwareVersion())
            {
                System.err.println("Firmware version invalid.");
                mStatusLabel.setText("Firmware version invalid.");
                return; //We can't connect without knowing firmware version                
            }
            
            //Create and open the home screen
            Point lLocation = this.getLocation();
            if(null == mHomeScreen)
            {
                mHomeScreen = new HomeScreen(this,
                                             mTargetSettings,
                                             mMessageRcvr,
                                             mMessageSndr);
            }
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    mHomeScreen.setLocation(lLocation);
                    mHomeScreen.setVisible(true);
                }
            });
            
            this.setVisible(false);
            mStatusLabel.setText("");
        }
	else
        {
            mStatusLabel.setText("Unable to open the COM port.");
            System.out.println("Unable to open the COM port.");
            
            JOptionPane.showMessageDialog(this,
                                          "Connection failed.",
                                          "Connect Failure",
                                          JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_mConnectButtonActionPerformed

    private void mInstallFirmwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInstallFirmwareButtonActionPerformed
        String lcComPortStr = (String) mComPortComboBox.getSelectedItem();

        if(mFwInstallScreen != null)
        {
            mFwInstallScreen = null;
            System.gc();
        }
        mFwInstallScreen = new FirmwareInstallerScreen(lcComPortStr);
        mFwInstallScreen.SetConnectScreen(this);
        mFwInstallScreen.setVisible(true);
        this.setVisible(false);
        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                mConnectButton.setEnabled(false);
//                mInstallFirmwareButton.setEnabled(false);
//                System.out.println("Selected COM Port: " + lcComPortStr);
//                
//                try
//                {
//                    Thread.sleep(1000);
//                }
//                catch(InterruptedException lEx)
//                {
//                    //Who cares?
//                }
//                
//                mConnectButton.setEnabled(true);
//                mInstallFirmwareButton.setEnabled(false);
//            }
//        });
                    
        
    }//GEN-LAST:event_mInstallFirmwareButtonActionPerformed

    public void Disconnect()
    {
        if(null != mMessageRcvr)
        {
            mMessageRcvr.Stop();
            mMessageRcvr = null;
        }
        
        if(null != mMessageSndr)
        {
            mMessageSndr = null;
        }
        
        if(null != mSerialPort)
        {
            mSerialPort.closePort();
            mSerialPort = null;
        }
        
        mAckCount = 0;
        
        System.gc();
        
        System.out.println("Disconnected.");
    }
    
    public void CloseHomeScreen()
    {
        mHomeScreen.setVisible(false);
        setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectScreen().setVisible(true);
            }
        });
        
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> mComPortComboBox;
    private javax.swing.JButton mConnectButton;
    private javax.swing.JButton mInstallFirmwareButton;
    private javax.swing.JLabel mStatusLabel;
    // End of variables declaration//GEN-END:variables


    private SerialPort[] mPorts;
    SerialPort mSerialPort;
    
    ResponseMessageReceiver mMessageRcvr;
    CommandMessageSender mMessageSndr;
    
    TargetSettingsManager mTargetSettings;
    
    HomeScreen mHomeScreen;
    FirmwareInstallerScreen mFwInstallScreen;
    int mAckCount;
}
