/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import java.io.File;
import java.util.HashMap;

/**
 *
 * @author Jake
 */
public class FirmwareInstallerScreen extends javax.swing.JFrame {

    /**
     * Creates new form FirmwareInstallerScreen
     */
    public FirmwareInstallerScreen(String aComPortStr) {
        initComponents();
        mComPortStr = aComPortStr;
        String lcMsg = "Will install firmware to " + aComPortStr + ".";
        mStatusText.setText(lcMsg);
        
        BuildFirmwareHashmap();
    }

    public void SetConnectScreen(ConnectScreen aScr)
    {
        mConnectScreen = aScr;
    }
    
    private void BuildFirmwareHashmap()
    {
        mFirmwareMap = new HashMap();
        String lcBaseDir = System.getProperty("user.dir");
        System.out.println("Starting DIR:" + lcBaseDir);
        
        mFirmwareMap.put("DIYino Stardust V3", lcBaseDir + "\\firmware\\DIYinoStardustV3.hex");
        mFirmwareMap.put("DIYino Stardust V3 Pixel", lcBaseDir + "\\firmware\\DIYinoStardustV3_Pixel.hex");
        mFirmwareMap.put("DIYino Prime V1", lcBaseDir + "\\firmware\\DIYinoPrimeV1.hex");
        mFirmwareMap.put("DIYino Prime V1 Pixel", lcBaseDir + "\\firmware\\DIYinoPrimeV1_Pixel.hex");
        mFirmwareMap.put("Brewboard", lcBaseDir + "\\firmware\\Brewboard.hex");
        mFirmwareMap.put("Brewboard Pixel", lcBaseDir + "\\firmware\\Brewboard_Pixel.hex");
        //mFirmwareMap.put("DIYino Proto V1", lcBaseDir + "\\firmware\\DIYinoProtoV1.hex");
        //mFirmwareMap.put("JakeSoft Test Platform", lcBaseDir + "\\firmware\\JakeSoftTestPlatform.hex");
        //mFirmwareMap.put("DIYino Prime V1 (JakeSoft's Pinout)", lcBaseDir + "\\firmware\\DIYinoPrimeV1JakeSoftPinout.hex");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTargetSelectComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        mInstallButton = new javax.swing.JButton();
        mCancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mStatusText = new javax.swing.JLabel();
        mBaudRateComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("JakeSoft's STREAM - Firmware Installer");

        mTargetSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIYino Prime V1", "DIYino Prime V1 Pixel", "DIYino Stardust V3", "DIYino Stardust V3 Pixel", "Brewboard", "Brewboard Pixel", " " }));
        mTargetSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTargetSelectComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Target");

        mInstallButton.setText("Install");
        mInstallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInstallButtonActionPerformed(evt);
            }
        });

        mCancelButton.setText("Cancel");
        mCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancelButtonActionPerformed(evt);
            }
        });

        mStatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mStatusText.setText("jLabel3");

        mBaudRateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "115200", "57600", " " }));

        jLabel3.setText("Baud Rate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mBaudRateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mTargetSelectComboBox, 0, 227, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mInstallButton)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mCancelButton)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mStatusText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mStatusText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTargetSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(mInstallButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mBaudRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(mCancelButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mInstallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInstallButtonActionPerformed
               
        String lFirmwareNameStr = (String)mTargetSelectComboBox.getSelectedItem();
        String lBaudRateStr = (String)mBaudRateComboBox.getSelectedItem();
        Integer lBaudRate = Integer.parseInt(lBaudRateStr);
        
        try{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Selected COM Port: " + mComPortStr);
                System.out.println("Selected Fimrware: " + lFirmwareNameStr);
                mStatusText.setText("Uploading...");
                mStatusText.repaint();
            }
        });
        
        }
        catch(Exception lEx)
        {
            lEx.printStackTrace();
            System.out.print(lEx.getMessage());
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //Figure out log file path
//                String lcLogFile = System.getProperty("user.dir");
//                lcLogFile += "\\FirmwareUpload.log";
                //Figure out firmware path
                String lcFirmware = mFirmwareMap.get(lFirmwareNameStr);
                
                FirmwareUploader lUploader
                        = new FirmwareUploader(mComPortStr, lcFirmware);
                lUploader.SetBaudRate(lBaudRate);
//                lUploader.SetLogFileName(lcLogFile);
                
                boolean lbSuccess = lUploader.Upload();

                try {
                    Thread.sleep(30000);
                } catch (InterruptedException lEx) {
                    //Who cares?
                }
                
                if(lbSuccess)
                {
                    setVisible(false);
                    mConnectScreen.setVisible(true);
                }
                else
                {
                    mStatusText.setText("Upload failed.");
                    mInstallButton.setEnabled(false);
                }
            }
        });

    }//GEN-LAST:event_mInstallButtonActionPerformed

    private void mCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancelButtonActionPerformed
        if(null != this.mConnectScreen)
        {
            mConnectScreen.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_mCancelButtonActionPerformed

    private void mTargetSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTargetSelectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTargetSelectComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> mBaudRateComboBox;
    private javax.swing.JButton mCancelButton;
    private javax.swing.JButton mInstallButton;
    private javax.swing.JLabel mStatusText;
    private javax.swing.JComboBox<String> mTargetSelectComboBox;
    // End of variables declaration//GEN-END:variables
    protected String mComPortStr;
    protected ConnectScreen mConnectScreen;
    
    protected HashMap<String,String> mFirmwareMap;
}
