/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author Jake
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(ConnectScreen aConnectScreen,
                      TargetSettingsManager aSettingsMgr,
                      ResponseMessages.ResponseMessageReceiver aRcvr,
                      CommandMessages.CommandMessageSender aSndr)
    {
        initComponents();
        
        this.setBackground(Color.black);
        this.getContentPane().setBackground(Color.black);
        this.setTitle("JakeSoft's STREAM " + Constants.VERSION + " - Home");
        
        mConnectScreen = aConnectScreen;
        mSettingsMgr = aSettingsMgr;
        mSettingsMgr.FetchSettingsFromTarget();
        
        mRcvr = aRcvr;
        mSndr = aSndr;
        
        PopulateSelectProfileComboBox();
        mEnableProfileSwitching = true;
        
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/STREAM.png")));
    }

    private void PopulateSelectProfileComboBox()
    {
        //Fetch list of options
        int lSelectedProfileIdx = (int)mSettingsMgr.GetSaberInfo().mSelectedProfileIndex;
        Integer lNumProfiles = (int)mSettingsMgr.GetSaberInfo().mNumberOfProfiles;
        
        ArrayList<Integer> lProfileList = new ArrayList();
        
        for(int lIdx = 0; lIdx < lNumProfiles; lIdx++)
        {
            System.out.print("Adding profile option:");
            System.out.println(lIdx);
            lProfileList.add(lIdx);
        }
        
        mProfileSelectComboBox.removeAllItems();
        for(Integer lItem : lProfileList)
        {
            mProfileSelectComboBox.addItem(lItem.toString());
        }

        //Now set the selected item in the combo box to be the current profile
        mProfileSelectComboBox.setSelectedIndex(lSelectedProfileIdx);
    }
    
    public HomeScreen() {
        initComponents();
        
        this.setBackground(Color.black);
        this.getContentPane().setBackground(Color.black);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BladeButton = new javax.swing.JButton();
        mSoundButton = new javax.swing.JButton();
        mMotionButton = new javax.swing.JButton();
        mOptionsButton = new javax.swing.JButton();
        mTipLabel = new javax.swing.JLabel();
        mDisconnectButton = new javax.swing.JButton();
        mQuitButton = new javax.swing.JButton();
        mSaveButton = new javax.swing.JButton();
        mLoadDefaultSettingsButton = new javax.swing.JButton();
        mProfileSelectComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JakeSoft's STREAM Beta 1");
        setBackground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(800, 330));
        setResizable(false);

        BladeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Blade.png"))); // NOI18N
        BladeButton.setMaximumSize(new java.awt.Dimension(100, 100));
        BladeButton.setMinimumSize(new java.awt.Dimension(100, 100));
        BladeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Blade_RollOver.png"))); // NOI18N
        BladeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BladeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BladeButtonMouseExited(evt);
            }
        });
        BladeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BladeButtonActionPerformed(evt);
            }
        });

        mSoundButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SoundTiming.png"))); // NOI18N
        mSoundButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/SoundTiming_RollOver.png"))); // NOI18N
        mSoundButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mSoundButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mSoundButtonMouseExited(evt);
            }
        });
        mSoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSoundButtonActionPerformed(evt);
            }
        });

        mMotionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Motion.png"))); // NOI18N
        mMotionButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Motion_RollOver.png"))); // NOI18N
        mMotionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mMotionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mMotionButtonMouseExited(evt);
            }
        });
        mMotionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMotionButtonActionPerformed(evt);
            }
        });

        mOptionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Options.png"))); // NOI18N
        mOptionsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Options_RollOver.png"))); // NOI18N
        mOptionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mOptionsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mOptionsButtonMouseExited(evt);
            }
        });
        mOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOptionsButtonActionPerformed(evt);
            }
        });

        mTipLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mTipLabel.setForeground(new java.awt.Color(0, 255, 255));
        mTipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mDisconnectButton.setBackground(new java.awt.Color(0, 0, 0));
        mDisconnectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Disconnect.png"))); // NOI18N
        mDisconnectButton.setBorder(null);
        mDisconnectButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Disconnect_RollOver.png"))); // NOI18N
        mDisconnectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mDisconnectButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mDisconnectButtonMouseExited(evt);
            }
        });
        mDisconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDisconnectButtonActionPerformed(evt);
            }
        });

        mQuitButton.setBackground(new java.awt.Color(0, 0, 0));
        mQuitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Quit.png"))); // NOI18N
        mQuitButton.setBorder(null);
        mQuitButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Quit_RollOver.png"))); // NOI18N
        mQuitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mQuitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mQuitButtonMouseExited(evt);
            }
        });
        mQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mQuitButtonActionPerformed(evt);
            }
        });

        mSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        mSaveButton.setBorder(null);
        mSaveButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save_RollOver.png"))); // NOI18N
        mSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mSaveButtonMouseExited(evt);
            }
        });
        mSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveButtonActionPerformed(evt);
            }
        });

        mLoadDefaultSettingsButton.setBackground(new java.awt.Color(0, 0, 0));
        mLoadDefaultSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DefaultSettings.png"))); // NOI18N
        mLoadDefaultSettingsButton.setBorder(null);
        mLoadDefaultSettingsButton.setBorderPainted(false);
        mLoadDefaultSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mLoadDefaultSettingsButton.setFocusable(false);
        mLoadDefaultSettingsButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DefaultSettings_RollOver.png"))); // NOI18N
        mLoadDefaultSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mLoadDefaultSettingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mLoadDefaultSettingsButtonMouseExited(evt);
            }
        });
        mLoadDefaultSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoadDefaultSettingsButtonActionPerformed(evt);
            }
        });

        mProfileSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mProfileSelectComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mProfileSelectComboBoxItemStateChanged(evt);
            }
        });
        mProfileSelectComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mProfileSelectComboBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mProfileSelectComboBoxMouseExited(evt);
            }
        });
        mProfileSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProfileSelectComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mTipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(BladeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mSoundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mMotionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mProfileSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mLoadDefaultSettingsButton)
                        .addGap(7, 7, 7)
                        .addComponent(mDisconnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mQuitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mDisconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mLoadDefaultSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mProfileSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BladeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mSoundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mMotionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(mTipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BladeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BladeButtonMouseEntered
        mTipLabel.setText("Blade Effects and Colors");
    }//GEN-LAST:event_BladeButtonMouseEntered

    private void BladeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BladeButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_BladeButtonMouseExited

    private void mSoundButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSoundButtonMouseEntered
        mTipLabel.setText("Sound and Timing");
    }//GEN-LAST:event_mSoundButtonMouseEntered

    private void mSoundButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSoundButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mSoundButtonMouseExited

    private void mMotionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMotionButtonMouseEntered
       mTipLabel.setText("Motion Settings");
    }//GEN-LAST:event_mMotionButtonMouseEntered

    private void mMotionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMotionButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mMotionButtonMouseExited

    private void mOptionsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mOptionsButtonMouseEntered
        mTipLabel.setText("Options");
    }//GEN-LAST:event_mOptionsButtonMouseEntered

    private void mOptionsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mOptionsButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mOptionsButtonMouseExited

    private void mDisconnectButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDisconnectButtonMouseEntered
        mTipLabel.setText("Disconnect");
    }//GEN-LAST:event_mDisconnectButtonMouseEntered

    private void mDisconnectButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDisconnectButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mDisconnectButtonMouseExited

    private void mQuitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mQuitButtonMouseEntered
        mTipLabel.setText("Quit");
    }//GEN-LAST:event_mQuitButtonMouseEntered

    private void mQuitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mQuitButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mQuitButtonMouseExited

    private void mQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mQuitButtonActionPerformed
        mConnectScreen.Disconnect();
        System.exit(0);
    }//GEN-LAST:event_mQuitButtonActionPerformed

    private void mDisconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDisconnectButtonActionPerformed
        this.mSettingsMgr = null;
        this.mBladeScreen = null;
        this.mSoundScreen = null;
        
        System.gc();
        
        mConnectScreen.Disconnect();
        mConnectScreen.CloseHomeScreen();
        mConnectScreen.setLocation(this.getLocation());
        
        
    }//GEN-LAST:event_mDisconnectButtonActionPerformed

    private void BladeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BladeButtonActionPerformed
        if(null == mBladeScreen)
        {
            mBladeScreen = new BladeConfigScreen(mSndr, mRcvr, mSettingsMgr);
        }
        else
        {
            mBladeScreen.InitDisplay();
        }
        
        mBladeScreen.SetHomeScreen(this);
        mBladeScreen.UpdateDisplay();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mBladeScreen.setVisible(true);
            }
        });
        
        mBladeScreen.setBounds(this.getBounds());
        this.setVisible(false);
    }//GEN-LAST:event_BladeButtonActionPerformed

    private void mSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSaveButtonMouseEntered
        mTipLabel.setText("Save to Saber");
    }//GEN-LAST:event_mSaveButtonMouseEntered

    private void mSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSaveButtonMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mSaveButtonMouseExited

    private void mSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveButtonActionPerformed
        mSettingsMgr.SendSettingsToTarget();       
    }//GEN-LAST:event_mSaveButtonActionPerformed

    private void mSoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSoundButtonActionPerformed
        if(null == mSoundScreen)
        {
            mSoundScreen = new SoundConfigScreen(mSettingsMgr);
            mSoundScreen.SetHomeScreen(this);
            mSoundScreen.SetCommandSender(mSndr);
        }
        mSoundScreen.UpdateDisplay();
        mSoundScreen.setBounds(this.getBounds());
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mSoundScreen.setVisible(true);
            }
        });
        
        this.setVisible(false);
    }//GEN-LAST:event_mSoundButtonActionPerformed

    private void mLoadDefaultSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoadDefaultSettingsButtonActionPerformed
        Byte lMsgId = (byte)CommandMessages.MessageIds.eeCmdLoadDefaultSettings.ordinal();
        mSndr.SendOneByteMessage(lMsgId);
        
        try
        {
            Thread.sleep(1000);
        }
        catch(InterruptedException lEx)
        {
            lEx.printStackTrace();
        }
        
        //Reload settings from target
        mSettingsMgr.FetchSettingsFromTarget();
    }//GEN-LAST:event_mLoadDefaultSettingsButtonActionPerformed

    private void mLoadDefaultSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLoadDefaultSettingsButtonMouseEntered
        mTipLabel.setText("Load Factory Defaults");
    }//GEN-LAST:event_mLoadDefaultSettingsButtonMouseEntered

    private void mLoadDefaultSettingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLoadDefaultSettingsButtonMouseExited
         mTipLabel.setText("");
    }//GEN-LAST:event_mLoadDefaultSettingsButtonMouseExited

    private void mMotionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMotionButtonActionPerformed
        if(null == this.mMotionScreen)
        {
            mMotionScreen = new MotionConfigScreen(mSettingsMgr);
            mMotionScreen.SetHomeScreen(this);
        }
        
        mMotionScreen.UpdateDisplay();
        mMotionScreen.setBounds(this.getBounds());
        mMotionScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mMotionButtonActionPerformed

    private void mProfileSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProfileSelectComboBoxActionPerformed
        
        if(false == mEnableProfileSwitching)
        {
            //Do nothing
        }
        else
        {
            String lSelectedIdxStr = (String) mProfileSelectComboBox.getSelectedItem();
            System.out.println("Selected profile index STR: " + lSelectedIdxStr);
            Integer lProfileInt = Integer.parseInt(lSelectedIdxStr);
            System.out.println("Selected profile index INT: " + lProfileInt);

            //Build message to send
            CommandMessages.tSwitchProfileMsg lMsg = new CommandMessages.tSwitchProfileMsg();
            lMsg.mProfileIdx = lProfileInt.byteValue();

            //Send message to switch profile
            System.out.println("Sending command to switch to profile " + lSelectedIdxStr);
            mSndr.SendMessage(lMsg);

            try {
                Thread.sleep(100);
            } catch (InterruptedException lEx) {
                //Who cares?
            }
            
            //Reload settings from target
            mSettingsMgr.FetchSettingsFromTarget();
        }
    }//GEN-LAST:event_mProfileSelectComboBoxActionPerformed

    private void mProfileSelectComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mProfileSelectComboBoxItemStateChanged
        //Do nothing
    }//GEN-LAST:event_mProfileSelectComboBoxItemStateChanged

    private void mOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOptionsButtonActionPerformed
        //Get rid of the old options screen if one exists
        if(null != mOptionsScreen)
        {
            mOptionsScreen = null;
        }
        
        mOptionsScreen = new OptionsScreen(mSettingsMgr);
        mOptionsScreen.SetHomeScreen(this);
        mOptionsScreen.setBounds(this.getBounds());
        mOptionsScreen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mOptionsButtonActionPerformed

    private void mProfileSelectComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProfileSelectComboBoxMouseEntered
        mTipLabel.setText("Switch Profile");
    }//GEN-LAST:event_mProfileSelectComboBoxMouseEntered

    private void mProfileSelectComboBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProfileSelectComboBoxMouseExited
        mTipLabel.setText("");
    }//GEN-LAST:event_mProfileSelectComboBoxMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BladeButton;
    private javax.swing.JButton mDisconnectButton;
    private javax.swing.JButton mLoadDefaultSettingsButton;
    private javax.swing.JButton mMotionButton;
    private javax.swing.JButton mOptionsButton;
    private javax.swing.JComboBox<String> mProfileSelectComboBox;
    private javax.swing.JButton mQuitButton;
    private javax.swing.JButton mSaveButton;
    private javax.swing.JButton mSoundButton;
    private javax.swing.JLabel mTipLabel;
    // End of variables declaration//GEN-END:variables

    protected TargetSettingsManager mSettingsMgr;
    protected ResponseMessages.ResponseMessageReceiver mRcvr;
    protected CommandMessages.CommandMessageSender mSndr;
    protected ConnectScreen mConnectScreen;
    
    protected BladeConfigScreen mBladeScreen;
    protected SoundConfigScreen mSoundScreen;
    protected MotionConfigScreen mMotionScreen;
    protected OptionsScreen mOptionsScreen;
    
    protected boolean mEnableProfileSwitching = false;
}
