/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import Util.Converter;
import ResponseMessages.ResponseMessageSubscriber;
import CommandMessages.CommandMessageSender;
import ResponseMessages.ResponseMessageReceiver;
import com.fazecast.jSerialComm.SerialPort;
import CommandMessages.*;
import ResponseMessages.ResponseMessageBase;
import ResponseMessages.tFirmwareVersionDataMsg;
import ResponseMessages.tProtocolVersionDataMsg;
import ResponseMessages.tBladeConfigDataMsg;
import ResponseMessages.tSoundConfigDataMsg;
import ResponseMessages.tMotionConfigDataMsg;
import javax.swing.JOptionPane;

/**
 *
 * @author Jake
 */
public class MainScreen
    extends javax.swing.JFrame 
    implements ResponseMessageSubscriber {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();

        initComPortComboBox();
        
        mDisconnect.setEnabled(false);
        mAckCounter = 0;
        
    }

    @Override
    public void NotifyMessage(ResponseMessageBase aMsg)
    {
        if(ResponseMessages.MessageIds.eeAck.ordinal() == aMsg.mMsgId)
        {
            System.out.println("Ack got to subscriber.");
            
            mAckCounter++;
            mAckCountLabel.setText("Ack Count:" + mAckCounter.toString());
        }
        else if(ResponseMessages.MessageIds.eeFirmwareVersionData.ordinal() == aMsg.mMsgId)
        {
            tFirmwareVersionDataMsg lMsg = (tFirmwareVersionDataMsg)aMsg;
            
            Integer lVerMajor = (int)lMsg.mVersionMajor;
            Integer lVerMinor = (int)lMsg.mVersionMinor;
            
            //Update display with the answer
            mFirmwareVersionTextBox.setText(lVerMajor.toString() + "." + lVerMinor.toString());
        }
        else if(ResponseMessages.MessageIds.eeProtocolVersionData.ordinal() == aMsg.mMsgId)
        {
            tProtocolVersionDataMsg lMsg = (tProtocolVersionDataMsg)aMsg;
            
            Integer lVerMajor = (int)lMsg.mVersionMajor;
            Integer lVerMinor = (int)lMsg.mVersionMinor;
            
            mProtocolVersionTextBox.setText(lVerMajor.toString() + "." + lVerMinor.toString());
        }
        
    }
    /**
     * Initialize the Com port selection box with valid options.
     */
    private void initComPortComboBox()
    {
        
        //Fetch avaiable COM ports
        mPorts = SerialPort.getCommPorts();
        
        //Populate the com port selection combo box with available options
        int i = 0;
        for(SerialPort port : mPorts)
        {
           mComPortComboBox.addItem(port.getSystemPortName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mRequestAckButton = new javax.swing.JButton();
        mComPortComboBox = new javax.swing.JComboBox<>();
        mConnectButton = new javax.swing.JButton();
        mDisconnect = new javax.swing.JButton();
        mChnlSlider1 = new javax.swing.JSlider();
        mChnlSlider2 = new javax.swing.JSlider();
        mChnlSlider3 = new javax.swing.JSlider();
        mBladeOffButton = new javax.swing.JButton();
        mChnlSlider1Lbl = new javax.swing.JLabel();
        mChnlSlider2Lbl = new javax.swing.JLabel();
        mChnlSlider3Lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mRequestFirmwareVersionButton = new javax.swing.JButton();
        mRequestProtocolVersionButton = new javax.swing.JButton();
        mFirmwareVersionTextBox = new javax.swing.JTextField();
        mProtocolVersionTextBox = new javax.swing.JTextField();
        mAckCountLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        mPowerUpTimeSpinner = new javax.swing.JSpinner();
        mPowerDownTimeSpinner = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mStayOnTimeSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mFlickerEffectSpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        mExecutePwrUpDownTestButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        mRequestBladeSettingButton = new javax.swing.JButton();
        mRequestSoundSettingsButton = new javax.swing.JButton();
        mRequestMotionSettingsButton = new javax.swing.JButton();
        mBladeConfigButton = new javax.swing.JButton();
        mLoadTargetCfgButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JakeSoft's S.T.R.E.A.M. Demo");
        setResizable(false);

        mRequestAckButton.setText("RequestAck");
        mRequestAckButton.setEnabled(false);
        mRequestAckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestAckButtonActionPerformed(evt);
            }
        });

        mConnectButton.setText("Connect");
        mConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnectButtonActionPerformed(evt);
            }
        });

        mDisconnect.setText("Disconnect");
        mDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDisconnectActionPerformed(evt);
            }
        });

        mChnlSlider1.setMaximum(255);
        mChnlSlider1.setMinorTickSpacing(10);
        mChnlSlider1.setValue(0);
        mChnlSlider1.setEnabled(false);
        mChnlSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider1StateChanged(evt);
            }
        });

        mChnlSlider2.setMaximum(255);
        mChnlSlider2.setMinorTickSpacing(10);
        mChnlSlider2.setValue(0);
        mChnlSlider2.setEnabled(false);
        mChnlSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider2StateChanged(evt);
            }
        });

        mChnlSlider3.setMaximum(255);
        mChnlSlider3.setMinorTickSpacing(10);
        mChnlSlider3.setValue(0);
        mChnlSlider3.setEnabled(false);
        mChnlSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mChnlSlider3StateChanged(evt);
            }
        });

        mBladeOffButton.setText("Blade Off");
        mBladeOffButton.setEnabled(false);
        mBladeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBladeOffButtonActionPerformed(evt);
            }
        });

        mChnlSlider1Lbl.setText("0");

        mChnlSlider2Lbl.setText("0");

        mChnlSlider3Lbl.setText("0");

        jLabel1.setText("Channel 1");

        jLabel2.setText("Channel 2");

        jLabel3.setText("Channel 3");

        mRequestFirmwareVersionButton.setText("Request Firmware Ver");
        mRequestFirmwareVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestFirmwareVersionButtonActionPerformed(evt);
            }
        });

        mRequestProtocolVersionButton.setText("Request Protocol Ver");
        mRequestProtocolVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestProtocolVersionButtonActionPerformed(evt);
            }
        });

        mFirmwareVersionTextBox.setEnabled(false);

        mProtocolVersionTextBox.setEnabled(false);

        mAckCountLabel.setText("Ack Count: 0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Blade Controls");

        mPowerUpTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(1000, 1, 9999, 10));
        mPowerUpTimeSpinner.setEnabled(false);

        mPowerDownTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(1000, 1, 9999, 10));
        mPowerDownTimeSpinner.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Power Up Time");

        jLabel6.setText("Power Down Time");

        mStayOnTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        mStayOnTimeSpinner.setEnabled(false);

        jLabel7.setText("Stay on for");

        jLabel8.setText("s");

        jLabel9.setText("ms");

        jLabel10.setText("ms");

        mFlickerEffectSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        mFlickerEffectSpinner.setEnabled(false);

        jLabel11.setText("Apply Flicker Effect");

        mExecutePwrUpDownTestButton.setText("Execute Test");
        mExecutePwrUpDownTestButton.setEnabled(false);
        mExecutePwrUpDownTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExecutePwrUpDownTestButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Power Up / Power Down Test");

        mRequestBladeSettingButton.setText("Req Blade");
        mRequestBladeSettingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestBladeSettingButtonActionPerformed(evt);
            }
        });

        mRequestSoundSettingsButton.setText("Req Snd");
        mRequestSoundSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestSoundSettingsButtonActionPerformed(evt);
            }
        });

        mRequestMotionSettingsButton.setText("Req Motion");
        mRequestMotionSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequestMotionSettingsButtonActionPerformed(evt);
            }
        });

        mBladeConfigButton.setText("Blade Config");
        mBladeConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBladeConfigButtonActionPerformed(evt);
            }
        });

        mLoadTargetCfgButton.setText("Load Target Cfg");
        mLoadTargetCfgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoadTargetCfgButtonActionPerformed(evt);
            }
        });

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mChnlSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mChnlSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mChnlSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mChnlSlider3Lbl)
                                    .addComponent(mChnlSlider2Lbl)
                                    .addComponent(mChnlSlider1Lbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(mBladeOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mFlickerEffectSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mStayOnTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mPowerDownTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(mExecutePwrUpDownTestButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mPowerUpTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mComPortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mConnectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mDisconnect)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mRequestAckButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mAckCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mRequestProtocolVersionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mRequestFirmwareVersionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mFirmwareVersionTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(mProtocolVersionTextBox, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mRequestBladeSettingButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mRequestSoundSettingsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mRequestMotionSettingsButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mBladeConfigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HomeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mLoadTargetCfgButton)
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mComPortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mConnectButton)
                    .addComponent(mDisconnect)
                    .addComponent(mRequestBladeSettingButton)
                    .addComponent(mRequestSoundSettingsButton)
                    .addComponent(mRequestMotionSettingsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRequestFirmwareVersionButton)
                    .addComponent(mFirmwareVersionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mRequestAckButton)
                    .addComponent(mAckCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRequestProtocolVersionButton)
                    .addComponent(mProtocolVersionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mPowerUpTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mPowerDownTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mStayOnTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mFlickerEffectSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mExecutePwrUpDownTestButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mChnlSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mChnlSlider1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mChnlSlider2Lbl)
                                        .addComponent(mChnlSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(mChnlSlider3Lbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mChnlSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mBladeOffButton))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mBladeConfigButton)
                    .addComponent(mLoadTargetCfgButton)
                    .addComponent(HomeButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnectButtonActionPerformed
        System.out.println("Connecting...");
               
        int lSelectedComPort = mComPortComboBox.getSelectedIndex();
        
        mSerialPort = mPorts[lSelectedComPort];
        
        //Try to open the port
        if(mSerialPort.openPort())
        {
            System.out.println("Port opened successfully.");
            
            //Set connection parameters
            mSerialPort.setComPortParameters(9600, 8, 1, SerialPort.NO_PARITY);
            mSerialPort.setComPortTimeouts(SerialPort.TIMEOUT_READ_BLOCKING, 0, 0);
            mSerialPort.setComPortTimeouts(SerialPort.TIMEOUT_WRITE_BLOCKING, 0, 0);
        
            //Clear any garbage off the serial port
            while(mSerialPort.bytesAvailable() > 0)
            {
                byte[] lGarbageByte = new byte[1];
                mSerialPort.readBytes(lGarbageByte, 1);
            }
            
            //Set controls enablement states
            mConnectButton.setEnabled(false);
            mDisconnect.setEnabled(true);
            mRequestAckButton.setEnabled(true);
            mBladeOffButton.setEnabled(true);
            mChnlSlider1.setEnabled(true);
            mChnlSlider2.setEnabled(true);
            mChnlSlider3.setEnabled(true);
            mFlickerEffectSpinner.setEnabled(true);
            mPowerUpTimeSpinner.setEnabled(true);
            mPowerDownTimeSpinner.setEnabled(true);
            mStayOnTimeSpinner.setEnabled(true);
            mExecutePwrUpDownTestButton.setEnabled(true);
            mRequestFirmwareVersionButton.setEnabled(true);
            mRequestProtocolVersionButton.setEnabled(true);
            
            //Create message receiver
            mMessageRcvr = new ResponseMessageReceiver(mSerialPort);
            mMessageRcvr.Subscribe(this); //Subscribe for messages
            new Thread(mMessageRcvr).start();
            
            //Create message sender
            mMessageSndr = new CommandMessageSender(mSerialPort);
            
            //Create target settings manager
            mTargetSettings = new TargetSettingsManager(mMessageSndr, mMessageRcvr);
            mTargetSettings.Init();
            
            System.out.println("Connected.");
        }
	else
        {
            System.out.println("Unable to open the port.");
	}

    }//GEN-LAST:event_mConnectButtonActionPerformed

    private void mDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDisconnectActionPerformed
        if(null != mSerialPort)
        {
            mMessageRcvr.Stop();
            
            mSerialPort.closePort();
            
            //Set Controls states
            mConnectButton.setEnabled(true);
            mDisconnect.setEnabled(false);            
            mRequestAckButton.setEnabled(true);
            mBladeOffButton.setEnabled(true);
            mChnlSlider1.setEnabled(false);
            mChnlSlider2.setEnabled(false);
            mChnlSlider3.setEnabled(false);
            mFlickerEffectSpinner.setEnabled(false);
            mPowerUpTimeSpinner.setEnabled(false);
            mPowerDownTimeSpinner.setEnabled(false);
            mStayOnTimeSpinner.setEnabled(false);
            mExecutePwrUpDownTestButton.setEnabled(false);
            mRequestFirmwareVersionButton.setEnabled(false);
            mRequestProtocolVersionButton.setEnabled(false);
        }

    }//GEN-LAST:event_mDisconnectActionPerformed

    private void mRequestAckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestAckButtonActionPerformed
        
        //Create the message
        byte lMsgIdByte = (byte)CommandMessages.MessageIds.eeCmdRequestAck.ordinal();
        OneByteMsg lMsg = new OneByteMsg(lMsgIdByte);
        
        //Send the message
        mMessageSndr.SendMessage(lMsg);
    }//GEN-LAST:event_mRequestAckButtonActionPerformed

    private void mBladeOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBladeOffButtonActionPerformed
        //Turn on Blade
        CommandMessages.tBladeControlSetPowerMsg lSetPwrMsg = 
                new CommandMessages.tBladeControlSetPowerMsg();
        lSetPwrMsg.mPower = 0;
        mMessageSndr.SendMessage(lSetPwrMsg);
    }//GEN-LAST:event_mBladeOffButtonActionPerformed

    private void SendBladeChannelSettings(boolean aTurnOn)
    {
        Integer lValue0 = mChnlSlider1.getValue();
        Integer lValue1 = mChnlSlider2.getValue();
        Integer lValue2 = mChnlSlider3.getValue();
        
        mChnlSlider1Lbl.setText(lValue0.toString());
        mChnlSlider2Lbl.setText(lValue1.toString());
        mChnlSlider3Lbl.setText(lValue2.toString());
        
        //Set Channel 0
        tBladeControlSetChannelMsg lSetChnlMsg = new tBladeControlSetChannelMsg();
        lSetChnlMsg.mChannel = 0;
        lSetChnlMsg.mValue = lValue0.byteValue();
        mMessageSndr.SendMessage(lSetChnlMsg);
        
        //Set Channel 1
        lSetChnlMsg.mChannel = 1;
        lSetChnlMsg.mValue = lValue1.byteValue();
        mMessageSndr.SendMessage(lSetChnlMsg);
        
        //Set Channel 2
        lSetChnlMsg.mChannel = 2;
        lSetChnlMsg.mValue = lValue2.byteValue();
        mMessageSndr.SendMessage(lSetChnlMsg);        
        
        if(aTurnOn)
        {
            tBladeControlSetPowerMsg lSetPwrMsg = new tBladeControlSetPowerMsg();
            lSetPwrMsg.mPower = 1;
            mMessageSndr.SendMessage(lSetPwrMsg);
        }
    }
    
    private void mChnlSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider1StateChanged
        SendBladeChannelSettings(true);
    }//GEN-LAST:event_mChnlSlider1StateChanged

    private void mChnlSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider2StateChanged
        SendBladeChannelSettings(true);
    }//GEN-LAST:event_mChnlSlider2StateChanged

    private void mChnlSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mChnlSlider3StateChanged
        SendBladeChannelSettings(true);
    }//GEN-LAST:event_mChnlSlider3StateChanged

    private void mRequestFirmwareVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestFirmwareVersionButtonActionPerformed
        Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestFirmwareVersion.ordinal();
        OneByteMsg lReqProdIdMsg = new OneByteMsg(lMsgId.byteValue());
        
        mMessageSndr.SendMessage(lReqProdIdMsg);
    }//GEN-LAST:event_mRequestFirmwareVersionButtonActionPerformed

    private void mRequestProtocolVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestProtocolVersionButtonActionPerformed
        Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestProtocolVersion.ordinal();
        OneByteMsg lReqProdIdMsg = new OneByteMsg(lMsgId.byteValue());
        
        mMessageSndr.SendMessage(lReqProdIdMsg);
    }//GEN-LAST:event_mRequestProtocolVersionButtonActionPerformed

    private void mExecutePwrUpDownTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExecutePwrUpDownTestButtonActionPerformed
        Integer lChnl = mChnlSlider1.getValue();
        lChnl += mChnlSlider2.getValue();
        lChnl += mChnlSlider3.getValue();
        
        if(lChnl.equals(0))
        {
            JOptionPane.showMessageDialog
                (this,
                 "Blade channels are set to zero. The blade won't turn on! \n Use the sliders to set blade color and brightness first.",
                 "Error: Blade channels zero",
                 JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        //Set blade channels per user controls, but don't turn the blade on
        SendBladeChannelSettings(false);
        
        //Create the command message to start the test
        CommandMessages.tPowerUpPowerDownTestMsg lMsg =
                new CommandMessages.tPowerUpPowerDownTestMsg();
        
        Integer lPowerUpTime = (Integer)mPowerUpTimeSpinner.getValue();
        Integer lPowerDownTime = (Integer)mPowerDownTimeSpinner.getValue();
        Integer lStayOnDuration = (Integer)mStayOnTimeSpinner.getValue();
        Integer lFlickerEffect = (Integer)mFlickerEffectSpinner.getValue();
        
        lMsg.mPowerupTime = lPowerUpTime.shortValue();
        lMsg.mPowerdownTime = lPowerDownTime.shortValue();
        lMsg.mOnDuration = lStayOnDuration.byteValue();
        lMsg.mFlickerType = lFlickerEffect.byteValue();
        
        //Send the command to begin the test
        mMessageSndr.SendMessage(lMsg);
        
//        mExecutePwrUpDownTestButton.setEnabled(false);
        Sleep(lStayOnDuration*1000 + lPowerDownTime + lPowerUpTime);
//        mExecutePwrUpDownTestButton.setEnabled(true);
       
    }//GEN-LAST:event_mExecutePwrUpDownTestButtonActionPerformed

    private void mRequestBladeSettingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestBladeSettingButtonActionPerformed
        Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestBladeConfig.ordinal();
        OneByteMsg lReqBladeSettingsMsg = new OneByteMsg(lMsgId.byteValue());
        
        mMessageSndr.SendMessage(lReqBladeSettingsMsg);
    }//GEN-LAST:event_mRequestBladeSettingButtonActionPerformed

    private void mRequestSoundSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestSoundSettingsButtonActionPerformed
        Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestSoundConfig.ordinal();
        OneByteMsg lReqSoundSettingsMsg = new OneByteMsg(lMsgId.byteValue());
        
        mMessageSndr.SendMessage(lReqSoundSettingsMsg);
    }//GEN-LAST:event_mRequestSoundSettingsButtonActionPerformed

    private void mRequestMotionSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequestMotionSettingsButtonActionPerformed
        Integer lMsgId = CommandMessages.MessageIds.eeCmdRequestMotionConfig.ordinal();
        OneByteMsg lReqMotionSettingsMsg = new OneByteMsg(lMsgId.byteValue());
        
        mMessageSndr.SendMessage(lReqMotionSettingsMsg);
    }//GEN-LAST:event_mRequestMotionSettingsButtonActionPerformed

    private void mBladeConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBladeConfigButtonActionPerformed
        /* Create and display the blade config form */
        BladeConfigScreen lBladeScreen = new BladeConfigScreen(mMessageSndr, mMessageRcvr, mTargetSettings);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {lBladeScreen.setVisible(true);
            }
        });
       
    }//GEN-LAST:event_mBladeConfigButtonActionPerformed

    private void mLoadTargetCfgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoadTargetCfgButtonActionPerformed
        
        mTargetSettings.FetchSettingsFromTarget();
        
//        while(null == mTargetSettings.GetBladeConfig() || 
//              null == mTargetSettings.GetMotionConfig() ||
//              null == mTargetSettings.GetSoundConfig())
//        {
//            //Wait for settings to be loaded
//            System.out.println("Waiting for settings...");
//        }
//        
//        System.out.print("Blade.mFlashColorIndex=");
//        System.out.println(mTargetSettings.GetBladeConfig().mFlashColorIndex);
//        System.out.print("Blade.mFlickerIndex=");
//        System.out.println(mTargetSettings.GetBladeConfig().mFlickerIndex);
//        System.out.print("Blade.mMainColorIndex=");
//        System.out.println(mTargetSettings.GetBladeConfig().mMainColorIndex);
//        System.out.print("Blade.mMainColorIndex=");
        
        
        
        
    }//GEN-LAST:event_mLoadTargetCfgButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void Sleep(long aMillis)
    {
        try {
            Thread.sleep(aMillis);
        } catch (InterruptedException lEx) {

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mAckCountLabel;
    private javax.swing.JButton mBladeConfigButton;
    private javax.swing.JButton mBladeOffButton;
    private javax.swing.JSlider mChnlSlider1;
    private javax.swing.JLabel mChnlSlider1Lbl;
    private javax.swing.JSlider mChnlSlider2;
    private javax.swing.JLabel mChnlSlider2Lbl;
    private javax.swing.JSlider mChnlSlider3;
    private javax.swing.JLabel mChnlSlider3Lbl;
    private javax.swing.JComboBox<String> mComPortComboBox;
    private javax.swing.JButton mConnectButton;
    private javax.swing.JButton mDisconnect;
    private javax.swing.JButton mExecutePwrUpDownTestButton;
    private javax.swing.JTextField mFirmwareVersionTextBox;
    private javax.swing.JSpinner mFlickerEffectSpinner;
    private javax.swing.JButton mLoadTargetCfgButton;
    private javax.swing.JSpinner mPowerDownTimeSpinner;
    private javax.swing.JSpinner mPowerUpTimeSpinner;
    private javax.swing.JTextField mProtocolVersionTextBox;
    private javax.swing.JButton mRequestAckButton;
    private javax.swing.JButton mRequestBladeSettingButton;
    private javax.swing.JButton mRequestFirmwareVersionButton;
    private javax.swing.JButton mRequestMotionSettingsButton;
    private javax.swing.JButton mRequestProtocolVersionButton;
    private javax.swing.JButton mRequestSoundSettingsButton;
    private javax.swing.JSpinner mStayOnTimeSpinner;
    // End of variables declaration//GEN-END:variables

    private SerialPort[] mPorts;
    SerialPort mSerialPort;
    
    ResponseMessageReceiver mMessageRcvr;
    CommandMessageSender mMessageSndr;
    Integer mAckCounter;
    
    TargetSettingsManager mTargetSettings;
}
