/*
 This file is part of the STREAM Graphical User Interface program (STREAM GUI).

 STREAM GUI is free software: you can redistribute it
 and/or modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation, either version 3 of the License,
 or (at your option) any later version.

 The STREAM GUI software is distributed in the hope that it will be
 useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the software.  If not, see <http://www.gnu.org/licenses/>.
*/
package GUI;

import java.awt.Color;

/**
 *
 * @author Jake
 */
public class MotionConfigScreen extends javax.swing.JFrame {

    /**
     * Creates new form MotionConfigScreen
     */
    public MotionConfigScreen(TargetSettingsManager aSettingsMgr)
    {
        initComponents();
        this.setTitle("JakeSoft's STREAM " + Constants.VERSION + " - Motion");
        mSettingsMgr = aSettingsMgr;
        
        this.setBackground(Color.black);
        this.getContentPane().setBackground(Color.black);
    }

    public void SetMessageSender(CommandMessages.CommandMessageSender aMsgSndr)
    {
        mMessageSndr = aMsgSndr;
    }
    
    public void SetHomeScreen(HomeScreen aHomeScreen)
    {
        mHomeScreen = aHomeScreen;
    }
    
    public void UpdateDisplay()
    {
        Integer lSwingSmall = (int)mSettingsMgr.GetMotionConfig().mSwingSmallTol;
        Integer lSwingMed = (int)mSettingsMgr.GetMotionConfig().mSwingMediumTol;
        Integer lSwingLarge = (int)mSettingsMgr.GetMotionConfig().mSwingLargeTol;
        Integer lClash = (int)mSettingsMgr.GetMotionConfig().mClashTol;
        Integer lTwist = (int)mSettingsMgr.GetMotionConfig().mTwistTol;
        
        mSwingSmallTolSpinner.setValue(lSwingSmall);
        mSwingMedTolSpinner.setValue(lSwingMed);
        mSwingLargeTolSpinner.setValue(lSwingLarge);
        mClashTolSpinner.setValue(lClash);
        mTwistTolSpinner.setValue(lTwist);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        mSwingLargeTolSpinner = new javax.swing.JSpinner();
        mSwingMedTolSpinner = new javax.swing.JSpinner();
        mSwingSmallTolSpinner = new javax.swing.JSpinner();
        mClashTolSpinner = new javax.swing.JSpinner();
        mTwistTolSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mOkButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        mSwingLargeTolSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));

        mSwingMedTolSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));

        mSwingSmallTolSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));

        mClashTolSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));

        mTwistTolSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Large Swing Tolerance");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medium Swing Tolerance");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Small Swing Tolerance");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clash Tolerance");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Twist Tolerance");

        mOkButton.setText("OK");
        mOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOkButtonActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Motion_RollOver.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(102, 255, 255));
        jLabel7.setText("To use these settings, select \"user custom\" from the in-hilt menu system for clash or swing.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mSwingLargeTolSpinner)
                            .addComponent(mSwingMedTolSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(mSwingSmallTolSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(mClashTolSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(mTwistTolSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(mOkButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mSwingLargeTolSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mSwingMedTolSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mSwingSmallTolSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mClashTolSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mTwistTolSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mOkButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOkButtonActionPerformed
        UpdateSettingsMgr();
        UpdateDisplay();
        
        mHomeScreen.setBounds(this.getBounds());
        mHomeScreen.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mOkButtonActionPerformed

    private void UpdateSettingsMgr()
    {
        Settings.tMotionParameters lMotionConfig =
                mSettingsMgr.GetMotionConfig();
        
        Integer lSwingSmall = (Integer)this.mSwingSmallTolSpinner.getValue();
        Integer lSwingMed = (Integer)this.mSwingMedTolSpinner.getValue();
        Integer lSwingLarge = (Integer)this.mSwingLargeTolSpinner.getValue();
        Integer lClash = (Integer)this.mClashTolSpinner.getValue();
        Integer lTwist = (Integer)this.mTwistTolSpinner.getValue();
        
        lMotionConfig.mSwingSmallTol = lSwingSmall.shortValue();
        lMotionConfig.mSwingMediumTol = lSwingMed.shortValue();
        lMotionConfig.mSwingLargeTol = lSwingLarge.shortValue();
        lMotionConfig.mClashTol = lClash.shortValue();
        lMotionConfig.mTwistTol = lTwist.shortValue();
        
        mSettingsMgr.SetMotionConfig(lMotionConfig);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MotionConfigScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MotionConfigScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MotionConfigScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MotionConfigScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MotionConfigScreen().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner mClashTolSpinner;
    private javax.swing.JButton mOkButton;
    private javax.swing.JSpinner mSwingLargeTolSpinner;
    private javax.swing.JSpinner mSwingMedTolSpinner;
    private javax.swing.JSpinner mSwingSmallTolSpinner;
    private javax.swing.JSpinner mTwistTolSpinner;
    // End of variables declaration//GEN-END:variables

    TargetSettingsManager mSettingsMgr;
    CommandMessages.CommandMessageSender mMessageSndr;
    HomeScreen mHomeScreen;
}
